services:

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  statping:
    image: statping/statping
    ports:
      - '8080:8080'
    volumes:
      - ./status:/app
    stop_grace_period: 1m
    restart: unless-stopped
