services:

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  ## https://progetti.lab.tp.it/
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8081:80"
    environment:
      - PLUGIN_INSTALLER=true
      - MAIL_SMTP_HOSTNAME=smtp.gmail.com
      - MAIL_SMTP_PORT=587
      - MAIL_SMTP_USERNAME=javanile.develop@gmail.com
      - MAIL_SMTP_PASSWORD=jsrsvofkdpteueok
      - MAIL_SMTP_HELO_NAME=
      - MAIL_SMTP_ENCRYPTION=tls
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins

  ## https://wiki.yafb.net/
  dokuwiki:
    image: dokuwiki/dokuwiki:stable
    ports:
      - "8082:8080"
    volumes:
      - ./dokuwiki:/storage

  ## http://nodered.lab.tp.it/
  nodered:
    build: ./docker/nodered
    environment:
      - TZ=Europe/Rome
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data

