services:

  ## http://192.168.144.73:3012/
  cronicle:
    build: ./docker/cronicle
    ports:
      - "3012:3012"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./cronicle/data:/opt/cronicle/data:rw
      - ./cronicle/logs:/opt/cronicle/logs:rw
      - ./cronicle/plugins:/opt/cronicle/plugins:rw
      - /opt/iac:/opt/iac:ro
      - /root/.hosts:/root/.hosts:ro
