services:

  ## https://progetti.lab.tp.it/
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8081:80"
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins
