services:

  ## https://progetti.lab.tp.it/
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8081:80"
    environment:
      - PLUGIN_INSTALLER=true
      - MAIL_SMTP_HOSTNAME=smtp.gmail.com
      - MAIL_SMTP_PORT=587
      - MAIL_SMTP_USERNAME=javanile.develop@gmail.com
      - MAIL_SMTP_PASSWORD=jsrsvofkdpteueok
      - MAIL_SMTP_HELO_NAME=
      - MAIL_SMTP_ENCRYPTION=tls
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins

  ## http://192.168.144.72:1880/
  nodered:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data

