services:

  ## https://progetti.lab.tp.it/
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8081:80"
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins

  cronicle:
    image: soulteary/cronicle
    ports:
      - "3012:3012"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./cronicle/data:/opt/cronicle/data:rw
      - ./cronicle/logs:/opt/cronicle/logs:rw
      - ./cronicle/plugins:/opt/cronicle/plugins:rw
      - /opt/iac:/opt/iac:ro
