services:

  ## https://progetti.lab.tp.it/
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8081:80"
    environment:
      - PLUGIN_INSTALLER=true
      - MAIL_SMTP_HOSTNAME=smtp.gmail.com
      - MAIL_SMTP_PORT=587
      - MAIL_SMTP_USERNAME=javanile.develop@gmail.com
      - MAIL_SMTP_PASSWORD=jsrsvofkdpteueok
      - MAIL_SMTP_HELO_NAME=
      - MAIL_SMTP_ENCRYPTION=tls
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins


  cronicle:
    build: ./docker/cronicle
    ports:
      - "3012:3012"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./cronicle/data:/opt/cronicle/data:rw
      - ./cronicle/logs:/opt/cronicle/logs:rw
      - ./cronicle/plugins:/opt/cronicle/plugins:rw
      - /opt/iac:/opt/iac:ro
